"on":
  push:
    branches:
      - main
name: Deploy to soff-prod
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Github tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
        with:
          tagged_release: v0.56.1
      - name: Deploy stack
        timeout-minutes: 30
        run: exec porter apply
        env:
          PORTER_CLUSTER: "4295"
          PORTER_DEPLOYMENT_TARGET_ID: 6c7d90a1-bd47-48bf-9847-77feacfa6d30
          PORTER_HOST: https://dashboard.porter.run
          PORTER_PR_NUMBER: ${{ github.event.number }}
          PORTER_PROJECT: "13713"
          PORTER_REPO_NAME: ${{ github.event.repository.name }}
          PORTER_STACK_NAME: soff-prod
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_STACK_13713_4295 }}
